### ISSUE TITLE
Add numbers in front of seed words

### ISSUE THREAD

**Issue by HGBG** [aeternity/aepp-waellet#10]
**Describe the solution you'd like**
For enhanced user experience we can add numbers in front of each word. The seed can be presented in 2 columns.  ex. 
![Screenshot from 2019-07-02 16-46-54](https://user-images.githubusercontent.com/24923480/60517915-28f57a00-9ce9-11e9-8269-b0ee3e2b3102.png)
see attachment 

**Describe alternatives you've considered**
 At a later stage, if we implement 24 words seed, we can use this functionality to request the user to enter 'x' amount of words from the seed in a random principle for enhanced security.

**Comment by mradkov** [comment]
Fixed
