### ISSUE TITLE
Send AE deep link

### ISSUE THREAD

**Issue by bogdyak** [aeternity/aepp-waellet#108]
Is there already a deep link to send AE to another account providing all params in URI?
If yes, please give me an example of such URI

Or kind of web3 connection, which can open extension when calling sign transaction method?

Thank you in advance

**Comment by mradkov** [comment]
Check out https://github.com/waellet/waellet/wiki/Aepp

**Comment by bogdyak** [comment]
@mradkov Thank you. Works smooth. 
Is there also deep link to open aepp-base mobile/desktop?

I found [discussion](https://github.com/aeternity/aepp-base/pull/19) and PR, but couldn't get what is the final URI

Can you help with that as well?
