### ISSUE TITLE
 Sending funds to sub-account 

### ISSUE THREAD

**Issue by HGBG** [aeternity/aepp-waellet#12]
**Describe the bug**
I`m unable to send funds from "main" account to a sub-account. Nothing happens when I click on the selected account.

**To Reproduce**
1. Go to ' Account...' 
2. Click on 'Send...'
3. Scroll down to 'send to sub-account...'
4. nothing happens

**Expected behavior**
To be able to select the available account and send funds to it

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: FireFox

**Comment by mradkov** [comment]
Fixed in #9
