### ISSUE TITLE
Broken Back to account UI

### ISSUE THREAD

**Issue by HGBG** [aeternity/aepp-waellet#13]
**Describe the bug**
The text "Back to account" is in 2 lines.

**To Reproduce**
1. Go to 'account.'
2. Click on 'receive'
3. See the text in 2 lines

The same problem can be found in the "Transaction History" seen  
*To Reproduce**
1. Go to 'account.'
2. Click on 'whole transaction history'
3. Scroll down
4. See the text in 2 lines

**Expected behavior**
expected to see the button in one line, as shown when clicked on send button

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Mozilla FF

**Comment by mradkov** [comment]
Fixed
