### ISSUE TITLE
Display fiat rate of the tokens in the wallet

### ISSUE THREAD

**Issue by HGBG** [aeternity/aepp-waellet#17]
**Describe the solution you'd like**
I would like to be able to see the fiat (USD/ EUR) value of the tokens in the wallet.

the avrg price can be obtained from https://coinmarketcap.com/api/

**Comment by tmlee** [comment]
You may consider our API at http://www.coingecko.com/api
Easily query Aeternity price in USD and EUR with this endpoint
https://api.coingecko.com/api/v3/simple/price?ids=aeternity&vs_currencies=usd,eur

**Comment by vmangelovv** [comment]
Coinmarketcap API free version has a lot of limitation of use like the number of requests per day is 333 and per month 10 000. E.g. If i want to convert AE to two or three currencies i have to make two or three requests for every single currency... Тemporarily will use the Coingecko API until you say smth else. Its easy and cool. 
p.s. I dont know how accurate is the response with Coingecko but Metamask and Etherscan are using it

**Comment by mradkov** [comment]
@vmangelovv  This sounds reasonable.

@tmlee Thanks for your input here. Hope its okay to contact you if any issue arise using your API. :)

**Comment by tmlee** [comment]
@mradkov @vmangelovv thanks for your consideration. give it a shot, feel free to reach out to me if there is any issue
