### ISSUE TITLE
Fund security warning message

### ISSUE THREAD

**Issue by HGBG** [aeternity/aepp-waellet#18]
**Is your feature request related to a problem? Please describe.**
Some users might not be aware that the waellet does not store their key pair and also that we are unable to recover user account.

**Describe the solution you'd like**
To avoid confusion and to help the user understand the risk that if he does not store properly his private key and encrypting password he won`t be able to recover his account if he signs out. 

The message should say "Please make sure to keep safe your seedphrase safe! Waellet does not store and cannot recover your seephrase! It is your responsibility to keep it safe. If you loose access to your waellet, you will loose all your funds.

Tips on how to protect your funds
- Safe a backup on multiple places
- Remember your password to decrypt your waellet
- Never share the phase with anyone"

**Comment by mradkov** [comment]
Fixed in pull #20
