### ISSUE TITLE
Small UI problems or inconsistencies

### ISSUE THREAD

**Issue by Zvezdin** [aeternity/aepp-waellet#26]
**Describe the bug**
I noticed a couple of minor UI problems or inconsistencies in the latest version as follows:

- The public address is a pink text on pink background. Difficult to see
- Most back buttons are on the top left, but some are on the bottom left and with different style (e.g. on the TX details page)
- Secondary actions, such as the donate button, should be in a separate tab, not in the main menu with core functions to send and receive tokens.
- Some pages extend beyond the window boundaries (Due to a recent Firefox update).
- On the TX details page, when you click to copy the TX hask, it says "address copied", but this is not an address.

**Comment by mradkov** [comment]
The feedback and suggestions were all addressed and fixed.
