### ISSUE TITLE
Second loader

### ISSUE THREAD

**Issue by mradkov** [aeternity/aepp-waellet#47]
**Describe the bug**
Second loader is showing on screen.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/13139371/61462394-411cf880-a97b-11e9-97ee-d4d927196603.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser firefox
 - Version 67

**Comment by petarbaykov** [comment]
Fixed in https://github.com/aeternity/aepp-waellet/pull/43/commits/cf4b892e74cc4d067e34df9e94c72c7632d8608b
