### ISSUE TITLE
Utilities: sign/verify message

### ISSUE THREAD

**Issue by mradkov** [aeternity/aepp-waellet#56]
Add functionality to sign and verify signed message.

**Comment by vmangelovv** [comment]
Please, describe the solution you'd like. If it's possible give a concise description of what you want to happen.

**Comment by mradkov** [comment]
I suggest having a "Sign / Verify message" in the Utilities section. Where user will be able to cryptographically sign a message with their private key or verify a signed message that they've received from elsewhere.

I envision it as just a simple form consisted of a text field with 2 action buttons - "Sign" and "Verify" which are doing the actions respectively.

**Comment by mradkov** [comment]
The issue is related to this: https://github.com/waellet/waellet/issues/117
